apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.prod.yml convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: auth-server
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-server
      lbtype: external
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.prod.yml convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/sola-web-app-default: "true"
        io.kompose.service: auth-server
        lbtype: external
        app: auth-server
    spec:
      containers:
        - image: sensolockacrdev.azurecr.io/sola-web-app-auth-server:v3
          name: auth-server
          ports:
            - containerPort: 3080
              hostPort: 3080
              name: "3080-port"
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.prod.yml convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: auth-server
  name: auth-server
spec:
  ports:
    - name: "3080"
      port: 3080
      targetPort: 3080
      name: "3080-port"
  selector:
    io.kompose.service: auth-server
