#values.yml file
controller:
  replicaCount: 1
  service:
    annotations:
      service.beta.kubernetes.io/azure-pip-name: sensolockpipdev
      service.beta.kubernetes.io/azure-dns-label-name: sensolockdev